```{r, include=FALSE}
library(rmarkdown)
library(BiocChallenges)
library(magrittr)
library(gh)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

## Difficulty

`r BiocChallenges::format_difficulty(params)`.

## Challenge leader(s)

`r paste0(BiocChallenges::format_leaders(params), collapse = "\n")`

## Topics

`r paste0(BiocChallenges::format_topics(params), collapse = "\n")`

## Duration

A minimum of `r params$duration` is recommended for this challenge.

## Repositories

A list of GitHub repositories that participate in this challenge.

```{r, echo=FALSE, results='asis'}
gh_stargazer_count <- function(repo) {
    query <- gh::gh(sprintf("GET /repos/%s", repo))
    query$stargazers_count
}
if (length(params$repositories)) {
    tab <- data.frame(
        repository = sprintf('<i class="fab fa-github"></i> [%s](https://github.com/%s)', params$repositories, params$repositories),
        stargazers = vapply(params$repositories, gh_stargazer_count, numeric(1))
    ) %>% 
        dplyr::arrange(desc(stargazers))
    knitr::kable(tab, row.names = FALSE)
} else {
    cat("_No repository currently addresses this challenge._\n")
    cat("\n")
}
```
