---
title: "Instrumentation for genomic computing with Bioconductor"
author:
- name: Vince Carey
  affiliation: Harvard Medical School
  email: stvjc@channing.harvard.edu
abstract: |
  We will use the [collectl system](http://collectl.sourceforge.net/index.html),
  along with some functions available in the [Rcollectl package](https://github.com/vjcitn/Rcollectl),
  to analyze system resource consumption
  for various genomic computing tasks.  Ultimately we want to have a system
  for estimating resource needs for genomic analysis activities.
vignette: |
  %\VignetteIndexEntry{Instrumentation for genomic computing with Bioconductor}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
params:
  date: "2020-11-27"
  difficulty: "advanced"
  leaders:
    value:
      vjcitn: "Vince Carey"
  topics:
    - "Instrumentation"
  duration: "1 hour(s)"
  repositories:
    - "vjcitn/Rcollectl"
---

```{r, child="_challenge_base.Rmd"}
```

## Guidelines

Fork the original repository <i class="fab fa-github"></i> `r BiocStyle::Githubpkg("vjcitn/Rcollectl")`, working on a branch of your fork, and submitting a pull request when your contribution is ready for review.

You may contribute new R markdown files or edit existing ones.

The basic aims are to 

- understand and explain how [collectl](http://collectl.sourceforge.net/index.html) can be used to monitor resource consumption on linux-like systems (and beyond?)
- start collectl monitoring for a task such as RNA-seq differential expression analysis
- carry out the task during the monitoring session
- create the collectl report, and parse, model and interpret using Rcollectl tools (or creating new ones)
- develop tools for modeling results from a sequence of progressively larger test runs to
support general consumption estimation procedures

